title = ""

[author]
name = "Alesh Lerch"
image = "img/author.png"



# headline = "DevOps engineer & Cyber Security enthusiast. "
headline = "DevOps Engineer @ KM"
# headline = "DevOps Engineer @ KM | IT Consultant"
bio = "DevOps Engineer passionate about Italian cuisine and self-hosted solutions ✨"
links = [
    { github = "https://github.com/axeII" },
    { mastodon = "https://infosec.exchange/@axell" },
    { linkedin = "https://www.linkedin.com/in/ales-lerch" }
]
