title = ""

[author]
name = "Alesh Lerch"
image = "img/author.jpg"


headline = "DevOps/SRE Engineer @ CMG"
bio = "DevOps/SRE Engineer"
links = [
  { github = "https://github.com/axeII" },
  { linkedin = "https://www.linkedin.com/in/ales-lerch" },
]
