locale = "en"
title = "blog.axell.dev"

[params]
displayName = "English"
isoCode = "en"
dateFormat = "2 January 2006"
description = "Writing about DevOps, infrastructure, home labs, and macOS."

[params.author]
name = "Ales Lerch"
image = "img/author.jpg"
headline = "DevOps/SRE Engineer @ CMG"
bio = "Writing about DevOps/SRE, infrastructure, home labs, and the occasional deep dive into macOS stuff."
links = [
  { github = "https://github.com/axeII" },
  { linkedin = "https://www.linkedin.com/in/ales-lerch" },
]
