title = "axell.dev"

[author]
name = "Ales Lerch"
image = "img/author.jpg"
headline = "DevOps engineer & Cyber Security ambassador. "
bio = "Loves Italian cuisine, scuba diving and self-hosted stuff ✨."
links = [
    { github = "https://github.com/axeII" },
    { mastodon = "https://infosec.exchange/@axell" }
]
