title = ""

[author]
name = "Alesh Lerch"
image = "img/author.jpg"


# headline = "DevOps engineer & Cyber Security enthusiast. "
headline = "DevOps Engineer @ CMG"
# headline = "DevOps Engineer @ KM | IT Consultant"
bio = "DevOps Engineer, also climber and helldiver"
links = [
  { github = "https://github.com/axeII" },
  { mastodon = "https://infosec.exchange/@axell" },
  { linkedin = "https://www.linkedin.com/in/ales-lerch" },
]
