# config/_default/menus.toml
# [[main]]
#   name = "/home"
#   pageRef = "/"
#   weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Whoami"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

# [[main]]
#   pre = "github"
#   name = ""
#   url = "https://github.com/axeII"
#   weight = 30

# [[main]]
#   identifier = "mastodon"
#   pre = "mastodon"
#   url = "https://infosec.exchange/@axell"
#   weight = 40

# [[footer]]
#   showAppearanceSwitcher = true
#   # name = "Privacy"
  # url = "https://external-link"
