# config/_default/menus.toml
# [[main]]
#   name = "/home"
#   pageRef = "/"
#   weight = 10

# [[main]]
#   name = "/home"
#   pageRef = "/"
#   weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40

[[main]]
  name = "Resume"
  url = "https://resume.axell.dev/resume.pdf"
  weight = 50

[[main]]
  name = ""
  url = "https://github.com/axeII/axell.dev"
  pre = "github"
  weight = 60

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
