colorScheme = "blowfish"
enableSearch = true
showRelatedContent = true
relatedContentLimit = 3
# defaultBackgroundImage = "img/background.webp"
defaultBackgroundImage = "img/bg.webp"
# logo = "img/logo.png"
highlightCurrentMenuArea = true
smartTOC = true
mainSections = ['favorite']
[header]
# layout = "fixed"
layout = "fixed-fill-blur"
[homepage]
layout = "custom"
# layout = "background"
# homepageImage = "img/background.jpg"
colorScheme = "avocado"
showRecent = true
showRecentItems = 6
cardView = true
showMoreLink = true
# cardViewScreenWidth = true
[article]
showHero = true
heroStyle = "big" # this on is nice but play with it
# heroStyle = "thumbAndBackground"
showBreadcrumbs = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 3
showComments = true
showTaxonomies = true
[list]
# showSummary = true
showBreadcrumbs = true
showHero = true
heroStyle = "background"
showTableOfContents = true
# cardViewScreenWidth = true
# showCards = true
groupByYear = true
[footer]
showAppearanceSwitcher = true
