colorScheme = "blowfish"

enableSearch = true
enableCodeCopy = true

logo = "img/logo_inverted.png"
secondaryLogo = "img/logo.png"

showRelatedContent = true
relatedContentLimit = 3

defaultBackgroundImage = "img/bg.svg"
highlightCurrentMenuArea = true
autoSwitchAppearance = false
defaultAppearance = "dark"

mainSections = ['favorite']

smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed-fill-blur"

[homepage]
  layout = "custom"
  colorScheme = "avocado"
  showRecent = true
  showRecentItems = 6
  cardView = true
  showMoreLink = true
  showMoreLinkDest = '/posts'
  # cardViewScreenWidth = true

[article]
  showHero = true
  showAuthor = true
  heroStyle = "basic"
  showBreadcrumbs = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showPagination = true
  showAuthorsBadges = true
  showSummary = true
  showReadingTime = true
  showComments = true
  showTaxonomies = true
  showEdit = true
  editURL = "https://github.com/axeii/my-blog/tree/main/content"
  editAppendPath = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showSummary = false
  showTableOfContents = false
  showCards = true
  # groupByYear = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = true

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  groupByYear = false
  cardViewScreenWidth = false
  cardView = false

[footer]
  showAppearanceSwitcher = true
  showScrollToTop = true
