baseURL = 'axell.dev'
languageCode = 'en-us'
title = 'my blog'
enableRobotsTXT = true
summaryLength = 10
defaultBackgroundImage = "img/background.jpg"
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
