---
version: "3"

tasks:

  init:
    desc: Initialize workstation dependencies with Brew
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed.
    vars:
      DEPS: >-
        go
        hugo

  build:
    desc: Build project
    cmds:
      - rm -rf public
      - hugo -t blowfish

  dev:
    desc: Setup develop environment
    cmds:
      - hugo server -D -t blowfish
    preconditions:
    - { msg: "Missing kubeconform script", sh: "test -d themes/blowfish/static" }
